### ISSUE TITLE
"Stub" implementation of Analytics library, for unit testing.

### ISSUE THREAD

**Issue by noahlz** [segmentio/analytics-java#100]
We recently found some bugs in our code that integrates with the Analytics java library that would be impossible to catch in our unit tests with Mocks, because we would have to know details of the actual Analytics library implementation.

What we could use is a "stub" implementation of your library that, rather than connecting to the Segment IO service, runs an embedded mock of the service that simulates the service and rejects / fails invalid usage of the API. I.e. missing / incomplete data, malformed input, etc.

Thoughts?

**Comment by f2prateek** [comment]
There's a few ways you can do this:

1. The endpoint is configurable - https://github.com/segmentio/analytics-java/pull/99. You can point it to a mock web server.


2. You can set a custom http client with an interceptor (https://github.com/square/okhttp/wiki/Interceptors) that returns a canned 200 response.

3. You can use an transformer in testing, that will simply drop the message (similar to above).

This is ordered from most end to end to least end to end.
