### ISSUE TITLE
null cannot be sent as a value to a Map

### ISSUE THREAD

**Issue by bostonaholic** [segmentio/analytics-java#103]
`com.google.common.collect.ImmutableMap` does not allow for `null` keys or values.

https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/ImmutableMap.html

Since `analytics-java` is using this library internally, as an implementation detail, I believe it should be the responsibility of `analytics-java` to strip out all `null`s before calling `ImmutableMap.copyOf(...)` and `ImmutableMap.of(...)`.

This is because I can successfully instantiate other map-like data structures (`java.util.HashMap`) with `null` values.

**Comment by f2prateek** [comment]
This is documented and intentional https://github.com/segmentio/analytics-java/blob/4cf9c8b7ea5a27fc56d6d71625b93320de92c824/analytics-core/src/main/java/com/segment/analytics/messages/Message.java#L13-L21.

**Comment by bostonaholic** [comment]
Thanks.

After looking into it. Guava is in my classpath (nested dependency, I'm not using it directly). So I didn't think this was working as intended.
