### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by gerlowskija** [segmentio/analytics-java#104]
Hi all,

Wanted to start the discussion around pushing out a release in the near future.  My team would really like to make use of https://github.com/segmentio/analytics-java/pull/99, but it's not yet available in a published release that I know of.

Is there anything that would prevent getting a release out soon so that consumers can access recent changes?

**Comment by f2prateek** [comment]
@gerlowskija thanks for the reminder! Typically we keep changes on master published as snapshots for a few weeks. We're way overdue on releasing here - so I just published those today https://github.com/segmentio/analytics-java/blob/master/CHANGELOG.md#version-200-april-4th-2017.
