### ISSUE TITLE
upgrade okhttp version?

### ISSUE THREAD

**Issue by atambo** [segmentio/analytics-java#105]
Right now you are using `okhttp` version `2.2.0` which is 3 years old. I'm having issues using this library because it's using such an old version of `okhttp` and some of my other libraries that use `okhttp` use a newer version and the transitive dependency between them `okio` has API breaking changes. It would be awesome if you could upgrade to `okhttp` version `3.6.0` or later.

**Comment by f2prateek** [comment]
The version of Retrofit we use requires older OkHTTP (though there are ways to make okhttp3 work with Retrofit 1). We could upgrade both though. Send a PR!

**Comment by wilfreddenton** [comment]
```
Could not upload batch %s. Retrying., retrofit.RetrofitError: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2, TLS_1_1, TLS_1_0], supportsTlsExtensions=true), ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1]
```

I'm receiving the above error when uploading. I believe it has to do with the outdated okhttp client.

**Comment by f2prateek** [comment]
Hmmm its not clear what the error is. What's the error and how does okhttp 3 resolve it?

**Comment by wilfreddenton** [comment]
That is the error I am receiving. The reason why I think updating okhttp 3 will fix it is because the same issue occurred in another SDK https://github.com/watson-developer-cloud/java-sdk/issues/614#issuecomment-295461341. @germanattanasio said the fix was to update okhttp to version 3.8 +

**Comment by germanattanasio** [comment]
We work with the okhttp fix and the IBM team to add the missing TLS/SSL constants. I think @atambo is running his app using the IBM JDK and that's why he gets the error.

**Comment by f2prateek** [comment]
We don't need to update the library to use OkHttp. You can set a custom networking client in the builder. This client can be backed by OkHttp3 or any networking stack. Here's a Client implementation that uses Okhttp 3 (https://github.com/JakeWharton/retrofit1-okhttp3-client)


```
Analytics analytics = Analytics.builder(writeKey)
  .client(new Ok3Client(client))
  .build();
```

Source code in our library for setting the client 
https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L120..

**Comment by f2prateek** [comment]
@atambo @wilfreddenton @germanattanasio can you confirm the fix I suggested ^ is working for you.

**Comment by germanattanasio** [comment]
@atambo ^^

**Comment by atambo** [comment]
We couldn't have both versions of okhttp on the classpath so we had to shade the jar to change the package. Using a different client wouldn't really solve the issue of having an older version of the library on the classpath causing compatibility issues with other libraries.

**Comment by f2prateek** [comment]
Hmm... OHttp 3 is written in a way that you can use it with   older versions of OkHttp - http://jakewharton.com/java-interoperability-policy-for-major-version-updates/. Additionally, depending on the package manager you are using you can exclude transitive dependencies, e.g. with Gradle https://stackoverflow.com/questions/21764128/how-do-i-exclude-all-instances-of-a-transitive-dependency-when-using-gradle.

Otherwise, what you are saying is that multiple versions of OkHttp cannot be used together. In this case the reverse of the problem would exist as well, i.e. if our library would use OkHttp 3 but a user might want to use OkHttp 1 or OkHttp 2, but couldn't. In this case, us migrating doesn't solve much, we're just trading one incompatibility for the other.

**Comment by atambo** [comment]
The thing that has the incompatibility is the `okio` library which is a dependency of `okhttp` and when you use have the older `okhttp` on the classpath it will use the older version of the `okio` library and cause problems with the newer okhttp.

**Comment by f2prateek** [comment]
I see, can you describe the exact error you saw in more detail?

**Comment by greenkiwi** [comment]
We are also very interest in this.  We would like to move forward with other libraries that use Retrofit 2.3, but are very concerned about causing dependency issues.

**Comment by f2prateek** [comment]
Without knowing what the error @atambo was seeing it's hard to say what the issue is.

All I can say is I didn't see an issue when we tried it as I mentioned in https://github.com/segmentio/analytics-java/issues/105#issuecomment-325257676.
