### ISSUE TITLE
I cannot build this package

### ISSUE THREAD

**Issue by jacksonofalltrades** [segmentio/analytics-java#106]
When I try to build with gradle I get this:
analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java:34: error: cannot find symbol
    library.put("version", AnalyticsVersion.get());
                           ^
  symbol:   variable AnalyticsVersion
  location: class AnalyticsClient
1 error

**Comment by jacksonofalltrades** [comment]
I'm using Java 1.8

**Comment by f2prateek** [comment]
The library is built with maven, not Gradle. It's unlikely to work with Gradle as is, AnalyticsVersion is injected via a template https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java-templates/com/segment/analytics/internal/AnalyticsVersion.java

**Comment by jacksonofalltrades** [comment]
Your README has instructions for gradle. Please remove them if you're not going to support gradle.

**Comment by f2prateek** [comment]
The readme has instructions for consuming the library via Gradle. Not for building this project via Gradle.
