### ISSUE TITLE
CPU usage tweaking

### ISSUE THREAD

**Issue by atambo** [segmentio/analytics-java#107]
I have been noticing that there seems to be some significant CPU usage when using this library to sent an event per request. Can you think of any ways for me to tweak the CPU usage? Maybe tweaking the batch size? https://segment.com/docs/sources/server/java/#batching

**Comment by f2prateek** [comment]
Can you profile where you're seeing the significant CPU usage? My first guess would be most likely https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java#L106 but it looks pretty standard.

Depending on your request volume, tweaking the batch size might help. The library has to block a thread each time it makes a request. If you send 1000 events flushing one at a time, it'll add up quickly. But if you batch it them even into batches of 10, you'll cut the blocking time by a factor of 10. The default is 250, but you can go higher as long as the total batch size does not exceed 500kb.

**Comment by f2prateek** [comment]
Closing this, but if you could send a sample app (maybe as a PR to this repo) https://github.com/segmentio/analytics-java/blob/master/analytics-sample/src/main/java/sample/Main.java that'd be great so we can dig in more.
