### ISSUE TITLE
analytics-core: gson ISO8601DateAdapter passes stringified primitive instead of the primitive value to Iso8601Utils.parse()

### ISSUE THREAD

**Issue by diminished** [segmentio/analytics-java#135]
In ```com.segment.analytics.gson.ISO8601DateAdapter.deserialize()```,
```JsonElement.toString()``` will return a stringified JSON primitive (i.e. "\"value\"") instead of the actual string value (i.e. "value").  

```JsonElement.getAsString()``` will return the actual value and could be used in place of the ```JsonElement.toString()``` call for the argument to ```com.segment.analytics.gson.Iso8601Utils.parse(String date)```.

**Comment by f2prateek** [comment]
Good catch! Mind sending a fix? I don't think we actually use the `deserialize` method (it's implemented to satisfy the interface), but I could be wrong.

**Comment by diminished** [comment]
Thanks, will do!

**Comment by diminished** [comment]
Pull request opened: https://github.com/segmentio/analytics-java/pull/136
