### ISSUE TITLE
Infinite wait for enqueing

### ISSUE THREAD

**Issue by gitPratikSingh** [segmentio/analytics-java#141]
Hi. I am using a spring scheduler to send messages to segment database using this server side library. I am seeing that after 40-50 rounds to the scheduled job instances, a job instance is not completing because it is stuck indefinitely. Because of that no other instance of the same jobs are running afterwards. Are you guys aware of this issue?

**Comment by gitPratikSingh** [comment]
My best guess is that there is at least a blocking call in your java library, which gets invoked when I do enqueue which has no timeout?

**Comment by TeresaNesteby** [comment]
Hi @gitPratikSingh! Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.
