### ISSUE TITLE
Configurable retry count

### ISSUE THREAD

**Issue by michaelkwan** [segmentio/analytics-java#144]
Using version 2.1.1, there is no ability to configure how many retries to attempt; and according to the source, at most, the failure callback is not received for 2 days.  Can the client be enhanced to allow for configuration of retry attempts?

**Comment by pbassut** [comment]
Hello, sorry for the long wait on this.
That's definitely possible. Mind sharing your particular use case on why would want the retry count to go over 2 days?

**Comment by lubird** [comment]
This is definitely in the spec of how we want every library to behave. We should definitely implement this ability @pbassut.
