### ISSUE TITLE
analytics.flush wont really ensure everything is flushed

### ISSUE THREAD

**Issue by dkm199** [segmentio/analytics-java#153]
While I was using Analytics Java sdk to to send users information to segment from Moesif, I 
noticed the client library could be improved to let the application know when all the messages are sent over network, so application knows when to shutdown.

Explained below more details with code snippet 
   once the application calls analytics.enqueue, and then analytics.flush to forcefully flush all the messages to network, its not done synchronously. Flush sends a poison pill to blocking message queue and looper thread reads this poison message and sends all the messages to network in a future.
 So after the flush is called, its not guaranteed all the internal threads/futures are completed. since there are looper and future threads involved. So if application calls analytics.shutdown and shuts down jvm after flush, its not guaranteed that all messages are sent over the network, which is what I noticed in my testing, and work around is put thread.sleep after flush. It would be nice to not have to wait on the thread for arbitrary amount of time and have a better way to ensure that all messages are really flushed to network
![image](https://user-images.githubusercontent.com/6922402/58836384-8aa0c680-860d-11e9-815b-0cd16a7923cf.png)

**Comment by f2prateek** [comment]
You can use a plugin for this (here's an example of this use case https://github.com/segmentio/analytics-java/blob/master/analytics-sample/src/main/java/sample/BlockingFlush.java).

**Comment by iguanito** [comment]
I would recommend to update the documentation since it suggested to use `flush()` method at the end of the program.
See https://segment.com/docs/connections/sources/catalog/libraries/server/java/#how-do-i-flush-right-now

**Comment by jeffjnh** [comment]
> You can use a plugin for this (here's an example of this use case https://github.com/segmentio/analytics-java/blob/master/analytics-sample/src/main/java/sample/BlockingFlush.java).

I'm likely doing something stupid here, but I actually couldn't get that to work in the way that I would have expected. Are there any plans to make a blocking version of flush natively within the Analytics client? Feels like a piece of behavior that shouldn't have to be manually configured as a plugin
