### ISSUE TITLE
application unable to send context and integrations for identify

### ISSUE THREAD

**Issue by dkm199** [segmentio/analytics-java#154]
The public methods exposed to send Identify message provide no way to send context information or integrations information . Only method exposed is to send traits

**Comment by pbassut** [comment]
Sorry for wait on this one. We're working on it and will update this ASAP

**Comment by pbassut** [comment]
Hello, when you use the Message Builder it exposes those methods. 
```java
analytics.enqueue(TrackMessage.builder("Button Clicked")
    .userId("f4ca124298")
    .enableIntegration("All", false)
    .enableIntegration("Amplitude", true)
);
```
[Found here](https://segment.com/docs/connections/sources/catalog/libraries/server/java/) and [here](https://segment.com/docs/connections/sources/catalog/libraries/server/java/)

**Comment by nd4p90x** [comment]
Closing per last comment by pbassut, Thanks
