### ISSUE TITLE
Java live requires android.net.http

### ISSUE THREAD

**Issue by leonkyr** [segmentio/analytics-java#156]
I am developing a Java Server App and would like to send some data to Segement.io

I am getting this error

`Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle nl.topicus.bitbucket.webhooks [134]: Unable to resolve 134.0: missing requirement [134.0] osgi.wiring.package; (osgi.wiring.package=android.net.http)`

I added the dependency to pom
``` 
<dependency>
  <groupId>com.segment.analytics.java</groupId>
  <artifactId>analytics</artifactId>
  <version>2.1.1</version>
</dependency>```

**Comment by leonkyr** [comment]
@f2prateek

**Comment by pbassut** [comment]
Can you provide more information?
This happens on startup? 
What version of java are you trying to use it with?
This library shouldn't require anything specific to Android.

**Comment by leonkyr** [comment]
@pbassut 

what info do you need?
It happens on the start up.
Version - 2.1.1

It shouldn't, but it does.

Anyways, I don't think Segment provide good support.. nearly 1 year for a reply.

**Comment by pbassut** [comment]
Really sorry about the long wait.
Could you help setup a minimal reproduction example?

We'll be giving full attention to this.

**Comment by leonkyr** [comment]
@pbassut I have not time for this.

Cheers
