### ISSUE TITLE
Java execution cannot stop using default client

### ISSUE THREAD

**Issue by angyalfold** [segmentio/analytics-java#168]
Hi,

The issue which I'm noticing is that it takes an additional one minute to my program to exit after `AnalyticsClient#shutdown()` was called. I'm using the default settings, so the initialization of the `AnalyticsClient` looks something like this (with a valid API key of course):
```
        Analytics analytics = Analytics.builder("MY_API_KEY")
                .build();
```
I'm using segment analytics 2.1.1.

I made a bit of research myself and I found that by default the `Retrofit.Client` with which the `Analytics` class is instantiated is essentially an `OkHttpClient`. The default keep alive time in `okhttp3#ConnectionPool` is 60 seconds. What I assume happens here is that a `ConnectionPool`, which is essentially a `java.util.concurrent.Executor` waits 60 seconds after the last `flush()` was called and when that passes the `ConnectionPool` ceases to exist and then my program can finally stop.

I saw a [similar issue](https://github.com/segmentio/analytics-java/issues/51) from 2015, but I'm not sure how the provided solution is applicable here. 

So the issue which I'm raising here is essentially that the `shutdown()` call doesn't clean up all the threads properly which were created by Segment and therefore the execution hangs for an additional minute before the program could finally stop.

**Comment by angyalfold** [comment]
OkHttp does have a problem which might be related, see [this](https://github.com/square/okhttp/issues/5542) bug report. [The changes](https://github.com/square/okhttp/issues/5512) which are supposed to tackle this issue were introduced in OkHttp 4.3 but Analytics 2.1.1 uses okhttp-3.9.0.
Couldn't Analytics offer a different client by default? Or use OkHttp 4.3+?

**Comment by pbassut** [comment]
Interesting. I wonder how that isn't contradictory with the issue raised at https://github.com/segmentio/analytics-java/issues/164 which claimed it should be doing the thing you're saying it already is? Or maybe I jumped on the bandwagon here(as they're used to say in my country)

**Comment by pbassut** [comment]
Also, we're moving over to retrofit2. Not sure if that changes things here.

**Comment by angyalfold** [comment]
Hi pbassaut,
Thanks for getting back to this issue.
My understanding is that the problem is caused by the behaviour of okhttp-3.9. So I don't think that moving to retrofit2 would solve this if okhttp remains at the current version.
Also, I think that the problem which I raised doesn't necessarily contradict with the one you linked (#164 ). Because we don't know if they used OkHttpClient for the connection or not.
