### ISSUE TITLE
E2E tests seem to be broken

### ISSUE THREAD

**Issue by lubird** [segmentio/analytics-java#179]
Looks like E2E tests have been regularly broken for a long time in Circle. Defintion here: https://github.com/segmentio/analytics-java/blob/7c2e2e5284e7e96da3dfb0298118f279069cfe12/.circleci/config.yml#L69

Latest failure: https://app.circleci.com/pipelines/github/segmentio/analytics-java/5151/workflows/487802ba-93e2-43fe-8a0d-d66c5f75c6d8/jobs/48530

**Comment by nd4p90x** [comment]
Closed with merge of #182
