### ISSUE TITLE
NetworkExecutor queue is unbounded by default

### ISSUE THREAD

**Issue by jdcaperon** [segmentio/analytics-java#239]
The NetworkExecutor default uses an unbounded queue by default:

https://github.com/segmentio/analytics-java/blob/b540b0104611950a39159c607a54128eca8168a0/analytics/src/main/java/com/segment/analytics/Platform.java#L34-L36

> Creates an Executor that uses a single worker thread operating off an unbounded queue,

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newSingleThreadExecutor(java.util.concurrent.ThreadFactory)

This means that if you experience network issues and you produce messages faster than the epic 15 second timeout default on the HTTP client: 

https://github.com/segmentio/analytics-java/blob/b540b0104611950a39159c607a54128eca8168a0/analytics/src/main/java/com/segment/analytics/Platform.java#L24-L32

Your instance of analytics-java will OOM and crash. This is probably not a healthy default. Instead, it is probably favourable to use a bounded queue on the Network Executor with some reasonable default so that you can backpressure or throw messages away to not cause the Heap to overflow.

**Comment by pbassut** [comment]
You can always replace the default client though, right?

**Comment by pbassut** [comment]
Or you're proposing a new value for the default that suits most people needs? If so, what you think that would be?

**Comment by nd4p90x** [comment]
@jdcaperon If you need to, please re-open this issue.  Thank you.
