### ISSUE TITLE
Bug in `analytics-sample`, `BlockingFlush`, "Attempt to register more than 65535 parties for java.util.concurrent.Phaser"

### ISSUE THREAD

**Issue by CraigStuntzWillowTree** [segmentio/analytics-java#261]
In the `analytics-sample` code there is [a BlockingFlush plugin](https://github.com/segmentio/analytics-java/blob/54d7dfa63157d1b1012de65b4a992a89f6bbde1e/analytics-sample/src/main/java/sample/BlockingFlush.java) which uses `java.util.concurrent.Phaser` incorrectly.

The problem is if you actually try to use this in a production scenario it calls `phaser.register()` lots of times, but it never calls `phaser.arriveAndDeregister()`. Instead it calls `phaser.arrive()`. So after some time you will receive:

`java.lang.IllegalStateException: Attempt to register more than 65535 parties for java.util.concurrent.Phaser@6cb672ad[phase = 0 parties = 65535 arrived = 65534]`

I can't see how the `BlockingFlush` can work at all as-is. I think it needs to call `phaser.arriveAndDeregister()` instead?

**Comment by pbassut** [comment]
Well, it's just a sample to show how the library should be used. We don't expect people to leave that running for a long time. 

If you were to use that in a production environment, that you would probably have to adjust it accordingly. 
But maybe it's cool to have a fully functional sample code. 
PRs are welcome!

Good catch, btw.

**Comment by CraigStuntzWillowTree** [comment]
So with it changed to `phaser.arriveAndDeregister()` it seems to work correctly, although if another plugin throws an exception in either its `callback` or its `messageTransformer` method it will still fail. I don't consider it a robust solution, but something is clearly needed here as without this plugin there are orphaned messages left in the queue when I tear down `Analytics`. I think a robust solution probably involves changing `analytics-java` to expose the `AnalyticsClient.messageQueue.isEmpty()` method, so that a user of `Analytics` can wait until the queue is drained before destroying it.

**Comment by CraigStuntzWillowTree** [comment]
I am still having problems with too many registered parties to the phaser even after making this change. It happens less often, but it still happens. My guess is that `transform` and `success`/`failure` events are somehow not perfectly symmetrical. At any rate, I've replaced `BlockingFlush` with... nothing? And it seems to work. `AnalyticsClient` ensures that the queue is fully drained when you call `shutdown()` and that's all I really care about.

**Comment by pbassut** [comment]
Right. [That's done by placing a STOP signal into the queue](https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java#L221). So no shutdown happens until the runner gets to that STOP signal and starts the shutdown(by that point it already processed every message in the queue).

But glad you got it working the way you wanted!

**Comment by philgebhardt** [comment]
Anyone coming here looking for some more information, I've outlined what a change looks like, using `arriveAndDeregister`, along with a breakdown of how indefinite blocking can occur with the current example. https://github.com/segmentio/analytics-java/pull/471
