### ISSUE TITLE
Library does not capture HTTP error bodies

### ISSUE THREAD

**Issue by CraigStuntzWillowTree** [segmentio/analytics-java#265]
We are seeing 400 errors from Segment. Unfortunately, that's all we know, because [the library does not capture the error body when logging](https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java#L320). Could you please add the error body to the log? We would like to see what is going on!

(I do realize that I can get this from a custom `OkHttpClient`, and if this persists it may come to that, but given that I'm already getting a log message of the error, I would just like to have complete information on that.)

**Comment by pbassut** [comment]
This should be an easy one. We'll just raise the exception with whatever it is in the body, if anything.
