### ISSUE TITLE
setUploadURL can have no effect due to code in Analytics.build()

### ISSUE THREAD

**Issue by CraigStuntzWillowTree** [segmentio/analytics-java#272]
In `Analytics.java`, there is [this code](https://github.com/segmentio/analytics-java/blob/17885ceef1a829b3d9be7b6f2a5452da526beec8/analytics/src/main/java/com/segment/analytics/Analytics.java#L340):

```java
      if (endpoint == null) {
        endpoint = HttpUrl.parse(DEFAULT_ENDPOINT + DEFAULT_PATH);
      }

      if (endpoint == null && uploadURL != null) {
        endpoint = uploadURL;
      }
```

So if `endpoint` is null, set it to some non-null value. Then immediately test it against null.

Because of this, code like:

```java
Analytics analytics = Analytics.builder(writeKey)
    .setUploadURL("https://example.com/foo") // this line has no effect.
    .build();
```

...has no effect at all and the library uses `https://api.segment.io/v1/import/` instead of `https://example.com/foo`

**Comment by sylin218** [comment]
Do we have an ETA for this new version release?
