### ISSUE TITLE
Add module descriptiors to the public libraries

### ISSUE THREAD

**Issue by andrasfuchs** [segmentio/analytics-java#313]
I'm trying to use Segment as a module in my own module and it gives me a hard time, because `module-info.java` is missing from the analytics libraries.

You can test if a .jar has module information easily, for example `jar --file=analytics-3.1.3.jar --describe-module` returns the following:
```
No module descriptor found. Derived automatic module.

analytics@3.1.3 automatic
requires java.base mandated
contains com.segment.analytics
contains com.segment.analytics.internal
```

This causes a lot of headache, because the automatic module name is different from the full library name.

Could you include a simple module-info.java in your libraries, with just a few lines defining the module name as the full library name? 
It would look something like this:
```
module com.segment.analytics {
    exports com.segment.analytics
    requires ...
    requires ...
}
```

**Comment by jorgen25** [comment]
Hello @andrasfuchs  I looked into your comment and while its true that there is no module descriptor, Im not sure what you mean by the automatic module name being different from the full library name?

The Analytics object, the class you will have to instantiate and use the library through that, its on this package com.segment.analytics, the com.segment.analytics.internal package also exists (although you will interact with this library through the Analytics class as I mentioned) and the only requirement for adding the Analytics dependency to your individual project is some version of java installed (I have java 8/ 11 btw)

**Comment by andrasfuchs** [comment]
Hi, sorry for the late reply. I got frustrated with Segment and I decided back then before you answered, that I will not integrate it.

Now I'm ready to give it another try. I followed the [Java Quickstart instructions](https://segment.com/docs/connections/sources/catalog/libraries/server/java/quickstart/).

I use Java 17, IntelliJ IDEA 2022.1 and Gradle 7.3.
![image](https://user-images.githubusercontent.com/910321/170055077-fa99c9dd-d908-4a3c-a8b7-d4f885fe1667.png)

I added the following line to my `build.gradle` file's `dependencies` section:
`implementation 'com.segment.analytics.java:analytics:3.2.0'`

![image](https://user-images.githubusercontent.com/910321/170052743-0b9dd16e-522a-45cc-b613-08d755852c7f.png)

Then I had the option to refresh in the IDE, so I do so.
![image](https://user-images.githubusercontent.com/910321/170052937-6bd2e3e9-9a73-4b20-9d2e-af088ddfedc0.png)

I got an error and it looks like the Analytics class is somehow not exposed to me to use.
![image](https://user-images.githubusercontent.com/910321/170053427-b92f4afc-f677-449a-8220-f087a50b4978.png)

I probably do something wrong and I would greatly appreciate your help!

Thank you!


My original report was about the missing `module-info.java` in your library, because my back-then conclusion was that that is the reason I can't use the Segment library in my project. There was a strange mix-up with file names and namespaces because of it, but I can't remember the exact details.
Would adding the `module-info.java` cause any trouble for you?
