### ISSUE TITLE
Include working sample code in the Java docs

### ISSUE THREAD

**Issue by andrasfuchs** [segmentio/analytics-java#314]
I followed [the Java tutorial](https://segment.com/docs/connections/sources/catalog/libraries/server/java/) to get things running with Segment, but I got some errors, and it's still not working.

The first one was because newer Gradle versions support the `implementation` keyword instead of `compile` for defining dependencies.

You have this [in your docs](https://segment.com/docs/connections/sources/catalog/libraries/server/java/#install-the-library):
![image](https://user-images.githubusercontent.com/910321/150700550-346a7f32-f8b4-4b87-bdd5-77276c6977e0.png)

...but it's deprecated: https://docs.gradle.org/6.9.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

The second problem I ran into is that your sample code uses `ImmutableMap` which changed with the newer versions of the [guava](https://guava.dev/releases/19.0/api/docs/com/google/common/collect/ImmutableMap.Builder.html). 
Could you change the code to use a simple [HashMap](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html) instead?

Also, it would be great to have a working Java example project that we can run right away.

**Comment by nd4p90x** [comment]
[PR #2592](https://github.com/segmentio/segment-docs/pull/2592)
