### ISSUE TITLE
Is com.segment.analytics.Analytics thread-safe?

### ISSUE THREAD

**Issue by longtimeago** [segmentio/analytics-java#321]
Is it safe to create `Analytics` instance once and then inject it as a service (e.g. by Spring/Guice) to be called in different threads?

Can't find any word about that neither in API nor in doc https://segment.com/docs/connections/sources/catalog/libraries/server/java/

Thanks in advance :)

**Comment by lukesolar** [comment]
I'm also interested in knowing this. In a Spring Boot Service, can we create a single Analytics instance and use it from different Controllers etc.? 
Also, when the Spring Boot App is restarted (by Heroku in our case), will the Analytics call .flush() or would we need to ensure this ourselves?

**Comment by nd4p90x** [comment]
@jorgen25 Any thoughts on this?  Thanks

**Comment by jorgen25** [comment]
@longtimeago  hi!

Yes Analytics library  is thread safe  as it is an immutable object once its created. It also uses a LinkedBlockingQueue to process msgs which is a proven thread safe collection
Thanks!

**Comment by longtimeago** [comment]
@jorgen25 cool, thank you for the confirmation! :+1: 
Worth mentioning that in javadoc :)

**Comment by nd4p90x** [comment]
@jorgen25 Let me know where in the docs this should be represented and I will create a PR.  Thanks

**Comment by longtimeago** [comment]
@jorgen25 I'd say here https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L43 as this is the main entry point to the client and usually devs start seeking for such info from there :)
