### ISSUE TITLE
Refactor Flusher/AnalyticsClient to Work in Google Appengine

### ISSUE THREAD

**Issue by sappenin** [segmentio/analytics-java#34]
Google Appengine has restrictions around spawning threads, so the current implementation of Flusher.java doesn't work right in app engine.  See this page's "Threads" section for more details on how threads may be used in Appengine: https://cloud.google.com/appengine/docs/java/

**Comment by f2prateek** [comment]
@sappenin This will be possible in v2. Do you know of a ThreadFactory implementation that works for AppEngine?

**Comment by sappenin** [comment]
@f2prateek Threads are pretty tightly controlled in AppEngine.  The ThreadManager class you referenced is your only choice inside of AppEngine.  Last time I tested this, I was able to get the Segment library to work (sort of) with that ThreadManager, but the problem I ran into is that any threads created via ThreadManager#createThreadForCurrentRequest will terminate when the request terminates (at worst) or when the request deadline is met (at best).  I believe the request deadline is currently 60 seconds, so most of my flushing never occurred because the thread would terminate at unpredictable times.  Inside of ThreadManager, there's an alternative method called #createBackgroundThread, but this only works on "backends" and isn't available on a regular AppEngine front-end instance, which is what I am using.

As a work-around, I decided to create something similar to Flusher.java that uses the AppEngine task queues to communicate with Segment instead of a Thread.  In this case, when I want to send an analytics event to Segment, my AppengineFlusher schedules a task in the task queue, and the AppEngine frontend request can safely terminate whenever it wants.  At some point (fairly quickly) the task queue executes my scheduled analytics "task" and the task handler makes the call to segment.

It's probably possible to develop some sort of shared-state mechanism here that only makes the call to Segment every so often (e.g., when 100 events queue up), but the taskqueue+URL call is fairly cheap from a resource perspective on Google's side, so I elected to go that route.

Here's some hacky code I put together in a fork of this Segment project: 
https://github.com/theupswell/analytics-java

The relevent commit is here:  
https://github.com/theupswell/analytics-java/commit/bf8e573f6ea60260b66685206db591756d4f6cae

The most important class is AppengineFlusher.java.  Not saying this is production ready or anything, but should give you an idea of how this could work using TaskQueue.

**Comment by hankim813** [comment]
@f2prateek what's the status of this issue?

**Comment by f2prateek** [comment]
@hankim813 Still not implemented.

**Comment by sbeaujard** [comment]
what's the status of this issue? Implemented on V2 ?

**Comment by f2prateek** [comment]
@sbeaujard Still not implemented. The issue will be closed when it does get implemented. Happy to review PRs.

**Comment by f2prateek** [comment]
Tracking internally https://segment.atlassian.net/browse/LIB-117

**Comment by pooyaj** [comment]
Closing as stale
