### ISSUE TITLE
Including sentAt in the Batch body of the HTTP request forces the use of a segment server computed timestamp

### ISSUE THREAD

**Issue by sromocki** [segmentio/analytics-java#340]
Is it possible to not include the sentAt() in the Batch body as this then forces all requests to use Segment's calculated timestamp versus the client provided timestamp if they try and set one.  Usually when a client sets a timestamp its for historical reasons and so the client provided timestamp should be the single source of truth without any calculations around clock skew.

**Comment by sromocki** [comment]
Instead of removing it completely you could allow users of the library to set the sentAt timestamp so that we can set it to null if we're doing a historical import.

**Comment by pooyaj** [comment]
hey @sromocki, could you please check this PR to see if it solves for your case: https://github.com/segmentio/analytics-java/pull/345

**Comment by sromocki** [comment]
@pooyaj It needs to be accessible from the client library.  I need to be able to do builder.sentAt(null).

**Comment by sromocki** [comment]
@pooyaj It needs to be accessible from the client library.  I need to be able to do builder.sentAt(null).

**Comment by wenxi-zeng** [comment]
@sromocki just a clarification on the changes:
* you should now be able to modify the `sentAt` value in the batch payload through `builder.sentAt(value)` by passing a non-null value
* however, by default or by passing a null value will force the value to be `new Date()`

if you don't have an `sentAt` value and want to prevent a Segment computed value, try pass an empty string.
