### ISSUE TITLE
Analytics Java 3.2.0 does not attempt to send event if it exceeds 32kb and only logs error without returning it from function

### ISSUE THREAD

**Issue by edignot** [segmentio/analytics-java#341]
Analytics Java 3.2.0 does not attempt to send event, and it does not return anything if event payload exceeds 32kb. It only logs internally that the message is above the individual limit, but no value is returned from that function: https://github.com/segmentio/analytics-java/blob/3f79618b4eced393fdd0e6a191a390210834394d/analytics/src/main/java/com/segment/analytics/internal/AnalyticsClient.java#:~:text=if%20(messageByteSize%20%3C%3D%20MSG_MAX_SIZE,s%22%2C%20message.messageId())%3B
, which makes it impossible for customers to monitor “failed” deliveries in production. I know that when manually testing, log helps, but in production events that are exceeding 32kb are simply not queued and sent and since no value is returned, it becomes impossible to monitor this. 

Is it possible to either return some value from the function, so the customers can track why events are not being queued and sent?

**Comment by edsonjab** [comment]
Hi @edignot this [PR #349](https://github.com/segmentio/analytics-java/pull/349) solve your issue or do you want that method "enqueue" throw the exception?
