### ISSUE TITLE
Null traits

### ISSUE THREAD

**Issue by guimeira** [segmentio/analytics-java#351]
Today we came across the issue reported in #57 and #103 where after adding Guava to the classpath, all attempts to send an event with null traits/properties results in a NullPointerException.
I couldn't find in the Segment docs any mentions of the expected behavior when a null value is sent as a trait, but upon some testing, it looks like there is a difference between sending a null trait and not including that trait in the map. If a user already has trait `x` (from a previous identify) and we send an identify event with `x=null`, this seems to "unset" `x` for that user. Whereas, if we send an identify event that does not contain `x` in the map of traits, the existing value of `x` seems to remain untouched.
During those tests, I noticed that this library is not able to send null traits, even when Guava is not present in the classpath, because it uses Gson to serialize the objects and [by default](https://github.com/google/gson/blob/master/UserGuide.md#null-object-support) Gson ignores null values.
So I'm wondering if this is an issue with the library or if this behavior we observed in Segment regarding null traits is not something we should rely on.
Thank you!!

**Comment by nd4p90x** [comment]
We have proposed this change to the docs to add clarification to this issue.
https://github.com/segmentio/segment-docs/pull/3005
