### ISSUE TITLE
Batches silently dropped in Flusher

### ISSUE THREAD

**Issue by jklukas** [segmentio/analytics-java#36]
Flusher does not check the return value of `requester.send` in https://github.com/segmentio/analytics-java/blob/master/src/main/java/com/github/segmentio/flush/Flusher.java#L99

I believe this led to data loss during this morning's Segment outage. Our service which sends data to Segment is configured to do 2 retries, with backoff and timeout set to 1 second each. Each time the flusher fires, I see a string of messages like this:
```
ERROR [2015-03-02 14:41:43,622] analytics: Failed analytics response. [error = Read timed out]
INFO  [2015-03-02 14:41:44,622] analytics: Retrying request [attempt 1] ..
ERROR [2015-03-02 14:41:45,691] analytics: Failed analytics response. [error = Read timed out]
INFO  [2015-03-02 14:41:46,691] analytics: Retrying request [attempt 2] ..
ERROR [2015-03-02 14:41:47,758] analytics: Failed analytics response. [error = Read timed out]
```
and then silence for usually a minute or more.

From my reading of the code, the [RetryingRequester returns false](https://github.com/segmentio/analytics-java/blob/analytics-1.0.4/src/main/java/com/github/segmentio/request/RetryingRequester.java#L38) in this case. The Flusher has already removed the message from the queue, and doesn't check the return value of `send` to see if it should requeue the batch.

Is it intended behavior that messages will be lost when a batch fails after the configured number of retries? Is it possible to configure the client to never drop batches?

**Comment by f2prateek** [comment]
Hey @jklukas, thanks for the report. I'll fix this soon.
