### ISSUE TITLE
Add Testing for IBM JVM

### ISSUE THREAD

**Issue by spencerattick** [segmentio/analytics-java#361]
Hey Team! I'm opening this issue to keep up to date on the work you all are doing (🙏) to add testing for IBM JVM. 

Here are the details for this change that I believe Pooya already shared:

> In looking at the available docker images,
>    [https://hub.docker.com/_/ibm-semeru-runtimes](https://urldefense.com/v3/__https://hub.docker.com/_/ibm-semeru-runtimes__;!!NCc8flgU!cTKpbS2u5gxB1vpgttGoOW_bzmOY0FcygGIttk_V3uQzEYSc8_9t20ZRg6pCgojjmAaDnGcYoIf90qhb$)
>    [https://hub.docker.com/r/ibmsemeruruntime/open-11-jdk](https://urldefense.com/v3/__https://hub.docker.com/r/ibmsemeruruntime/open-11-jdk__;!!NCc8flgU!cTKpbS2u5gxB1vpgttGoOW_bzmOY0FcygGIttk_V3uQzEYSc8_9t20ZRg6pCgojjmAaDnGcYoFucIKTi$)
> 
> I think I would probably pull the Semeru OpenJDK11
> docker pull ibm-semeru-runtimes:open-11.0.15_10-jdk-centos7
> 
> 
> add as test image,
> 
>   test-semerujdk11:
>     <<: *java-base-test
>     docker:
>       - image: ibm-semeru-runtimes:open-11.0.15_10-jdk-centos7
> 
> 
> 
> and then add to the list of tests:
> 
>   workflows:
>     version: 2
>     multi-test:
>       jobs:
>         - test-jdklatest
>         - test-jdk11
>         - test-jdk8
>         - test-semerujdk11

**Comment by spencerattick** [comment]
Hey @nd4p90x! Thanks so much for putting this into place! 🎉 Can you confirm the new tests you put in place ran without errors? The customer just wants to make sure.

**Comment by nd4p90x** [comment]
@spencerattick everything looks successful from our end.  Thank you.
