### ISSUE TITLE
mixpanel.people.increment()

### ISSUE THREAD

**Issue by angeloh** [segmentio/analytics-java#38]
How can I achieve mixpanel.people.increment() on segment java library?

**Comment by f2prateek** [comment]
You can simply set specific event name in our web app under advanced settings (http://cl.ly/image/3W0k0G111l34). Then if you send any event with names that you've set in the setting, they will be used to call increment. https://github.com/segmentio/integration-mixpanel/blob/master/lib/index.js#L116

Make sure you also have Mixpanel People enabled.

**Comment by sebastian-schlecht** [comment]
Is there any way to init the event count to zero in case the event never happened for a specific user?

**Comment by f2prateek** [comment]
Not afaik but please write in to support and they might have a solution https://segment.com/contact/support/integrations
