### ISSUE TITLE
Large message size for analytics.enqueue leads to thread interrupt

### ISSUE THREAD

**Issue by taylormathewson** [segmentio/analytics-java#397]
Observed in v3.3.1

When `analytics.enqueue` is called with a large message, Analytics client will check the size of the message.  If the max size (32kb) is exceeded a `java.lang.InterruptedException` is thrown.  This seems inappropriate, as that exception per its javadocs is:

> Thrown when a thread is waiting, sleeping, or otherwise occupied, and the thread is interrupted, either before or during the activity.

Further, this is caught further down in the method and `Thread.currentThread().interrupt();` is called, which is odd and very difficult to deal with, particularly it cannot be caught as an exception.
Not sure why this pattern is used, but something like an `IllegalArgumentException` would seem much more appropriate and allow for consuming code to handle a message being too large. 
With current scenario, it can't even be caught, and any `Callback.failure` is ignored as well.

I was able to work around by using `Thread.interrupted()` (which clears interrupted status from the thread) after calling `analytics.enqueue` but this is not optimal and a very brittle approach.  It requires that I assume that a Thread's interrupt status is used as an indicator for whether `analytics.enqueue` was successful.

```java
try{
    analytics.enqueue(largeMessage);
    if(Thread.interrupted()){
        analytics.enqueue(smallerMessage); // this works but it's terrible
    }
} catch (Exception e){
// not invoked but should be, preferably with a more specific exception
    log.error("got error enqueueing", e);
    analytics.enqueue(smallerMessage);
}
```

**Comment by edsonjab** [comment]
Hi @taylormathewson thank you for your report, we start looking into this.
