### ISSUE TITLE
[3.4.0] writeKey is not passed in Authorization header

### ISSUE THREAD

**Issue by jkovacs** [segmentio/analytics-java#418]
The most recent version (3.4.0) of `analytics-java` does not appear to pass the `writeKey` in the `Authorization` header anymore, whereas the previous versions (up to 3.3.1) still do.

This seems to have been a deliberate change as part of PR #408, however no justification for this change seems to be given.
This change makes it inconsistent with the other segment analytics libraries (e.g. python, go, csharp) and also contradicts the segment [specification](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#authentication) with respects to authentication.

Please consider reverting this particular part of the recent change.

**Comment by MichaelGHSeg** [comment]
Sorry for letting this fall through the cracks.  We were in the middle of updating the specification to address an issue and all of our libraries are being brought in line with this change.
