### ISSUE TITLE
Remove reliance on java.util.Date in favor of the newer Date-Time APIs

### ISSUE THREAD

**Issue by grimsa** [segmentio/analytics-java#430]
The classes in the current Segment Java SDK accept the old `java.util.Date` in method signatures, for example:
```
var message = TrackMessage.builder(event.documentName())
        .timestamp(java.util.Date.from(event.time()))      // <-- here we have to convert Instant to Date
        .userId(event.user().id())
        .properties(properties);
```

Java 8 introduced the new The Date-Time APIs (e.g. `java.time.Instant`), which are preferred over the old `java.util.Date/Calendar` for their immutability, thread safety, and expressiveness.

It seems it should be possible to add overloaded method versions to support the new Date-Time APIs without changing or removing the existing methods.

**Comment by edsonjab** [comment]
Hi @grimsa  thank you for your report, we start looking into this.

**Comment by MichaelGHSeg** [comment]
Thank you for the suggestion.  We're shifting development over to the new [Analytics-Kotlin](https://github.com/segmentio/analytics-kotlin) library, so we won't be changing the java interface at this time.  We'll try to keep updated types in mind over there (but at a glance it looks like the timestamp is currently a string :) ).
