### ISSUE TITLE
No analytics artifact 2.0.0-SNAPSHOT under apache repository

### ISSUE THREAD

**Issue by vkolodrevskiy** [segmentio/analytics-java#47]
Looks like apache snapshot repository does not contain analytics 2.0.0 dependencies.

**Comment by f2prateek** [comment]
It's not a tagged release yet - https://github.com/segmentio/analytics-java#snapshots

**Comment by vkolodrevskiy** [comment]
I've added snapshot repository, but not able to download dependency anyway.
Workaround was to manually install dependencies from the sources.

**Comment by f2prateek** [comment]
Ah sorry, I realized I copied the wrong example. Updated now with the correct URL. Thanks for pointing that out!

**Comment by vkolodrevskiy** [comment]
@f2prateek, do you trigger artifact snapshot deployment on every commit or it's per cron?

**Comment by f2prateek** [comment]
It's on every commit to the master branch.
