### ISSUE TITLE
Missing okio-jvm runtime dependency

### ISSUE THREAD

**Issue by jdelattr** [segmentio/analytics-java#478]
Hi,

I have added Segment Analytics 3.5.1 dependency, but it fails at runtime with "java.lang.NoClassDefFoundError: okio.Buffer".
Adding the dependency on okio-jvm fixes the error.

```
<dependency>
    <groupId>com.segment.analytics.java</groupId>
    <artifactId>analytics</artifactId>
    <version>3.5.1</version>
</dependency>
<!-- segment missing dep? fails at runtime without it:  java.lang.NoClassDefFoundError: okio.Buffer -->
<dependency>
    <groupId>com.squareup.okio</groupId>
    <artifactId>okio-jvm</artifactId>
    <version>3.9.0</version>
</dependency>
```

**Comment by edsonjab** [comment]
hi @jdelattr thank you for your report. We start working into this.

**Comment by edsonjab** [comment]
hi @jdelattr what version of java are you using?

**Comment by jdelattr** [comment]
Hi @edsonjab 
Here is the version I'm using:

```
IBM Semeru Runtime Open Edition 17.0.8.1 (build 17.0.8.1+1)
Eclipse OpenJ9 VM 17.0.8.1 (build openj9-0.40.0, JRE 17 Mac OS X aarch64-64-Bit 20230824_392 (JIT enabled, AOT enabled)
```

**Comment by jdelattr** [comment]
I've have just tested with a minimal project and do not reproduce. It must come from a specificity of the environment I'm trying to run in.
Closing the issue, sorry for the false positive.
