### ISSUE TITLE
Segment's MessageBuilder context is write-only which prevents additive context building

### ISSUE THREAD

**Issue by rvowles** [segmentio/analytics-java#486]
I am trying to add Segment integration for the Java SDK for FeatureHub (https://featurehub.io) - and I need to be able to capture the state of the features when a message is dropped to Segment. I want to augment the context, but if someone has another MessageTransformer which has set the context, I cannot add to that context (in the MessageBuilder), I can only overwrite it. I get we should create a new Map and stuff the existing data into it so we don't have cross SDK leakage, but we should be able to get the existing context.

**Comment by edsonjab** [comment]
Hi @rvowles thank you for your report, we start looking into this.
