### ISSUE TITLE
update javax annotations to jakarta annotations

### ISSUE THREAD

**Issue by rvowles** [segmentio/analytics-java#487]
There are a bunch of 

````
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
````

Annotations - is it possible to provide a variant that uses the more modern jakarta equivalent?

**Comment by edsonjab** [comment]
hi @rvowles could you help me to check this [PR](https://github.com/segmentio/analytics-java/pull/488) if is the solution that you need, please?
