### ISSUE TITLE
Api READ KEY what for.

### ISSUE THREAD

**Issue by vkolodrevskiy** [segmentio/analytics-java#53]
Hi,

Sorry for asking this question here, but there's no response from segment support on the website.

The question is: why is there READ KEY available in segment dashboard? What API methods are available for reading data?

**Comment by f2prateek** [comment]
It doesn't serve any purpose currently, it was originally created for some features that have since been deprecated.

**Comment by vkolodrevskiy** [comment]
Thank you.
