### ISSUE TITLE
Track if message was sent

### ISSUE THREAD

**Issue by vkolodrevskiy** [segmentio/analytics-java#54]
Hi,

We want to design a system that handles situation when there's no connection between client and segment api. We want to persist undelivered messages in order to send them again, say after application restart or when connection to segment api would be established again.

I'm looking at current java client and don't see any means to track whether messages were delivered, whether analytics client was able to connect to api endpoint(parsing logs is not a solution☺).

Are you guys gonna implement something like this? Is there any approach you can suggest for solving my problem with current java client?

Thank you.

**Comment by f2prateek** [comment]
Indeed, the right to do this (I think) would be return any in flight messages in the shutdown method. This way the application can control what do with them (in your case you'd simply save them and requeue them later).

Until I get time to add this though, the only other solution would be to use the [`core` module](https://github.com/segmentio/analytics-java/tree/master/analytics-core/src/main/java/com/segment/analytics) which defines all the model classes and HTTP server, and write your mechanism to define an upload policy. Basically you'd copy this class - https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java and replace the queue with something that you can persist to disk.

**Comment by mashapedeployment** [comment]
+1

**Comment by shashiranjan84** [comment]
+1

**Comment by f2prateek** [comment]
Callback API added with #75
