### ISSUE TITLE
document or fix inability to set null values

### ISSUE THREAD

**Issue by chrylis** [segmentio/analytics-java#57]
I passed the message builder a map with a `null` value, and this threw an exception when the builder tried to copy it into a Guava `ImmutableMap`, which doesn't permit null values. This limitation should be clearly documented if it's not practical to work around it.

**Comment by f2prateek** [comment]
Updated the behaviour so that null keys and values are allowed by default, unless we detect that Guava is available, in which case we document it's limitations.

```
/**
 * For any functions that accept a map, such as {@link #integrations()}, {@link #context()}, {@link
 * TrackMessage#properties()}, {@link ScreenMessage#properties()}, {@link IdentifyMessage#traits()},
 * or {@link GroupMessage#traits()}, we'll make an internal copy of the map provided. If you use
 * <a href="https://github.com/google/guava">Guava</a>, we'll use it's {@code ImmutableMap#copyOf}
 * methods instead.
 * <p>
 * There are a few limitations to be aware of when using Guava — mainly that null keys or values
 * are not permitted and duplicate keys are not permitted. For more details, refer to Guava's
 * <a href="http://bit.ly/1N5v3Cq">Javadocs</a>.
```

**Comment by hkothari** [comment]
Hi, we use dropwizard and a bunch of things that also use guava that we can't unfortunately take off the classpath. Sadly, we also would like to set a null value in segment and are doing so by providing a hashmap of properties. But then the segment code is forcing it into a guava map. Any way we can intentionally set null keys here? Or is it just totally impossible?

It's kind of unusual that your API specifies different behaviors tied to whatever happens to be on the classpath so not sure how to navigate this one.

cc: @shzhng
