### ISSUE TITLE
Builder#properties wants a Map<String,Object>

### ISSUE THREAD

**Issue by chrylis** [segmentio/analytics-java#63]
It appears that once the `.properties(map)` call is made, the value is treated as read-only for the remainder of its lifetime. If the library is not adding to the properties anywhere, it would be much easier (especially with dynamic languages such as Groovy) to change the signature to `Map<String,?>`, since the inferred type of most inline maps is either `<String,Serializable>` or `<String,String>`.

**Comment by f2prateek** [comment]
Yup I wanted it that way originally. I'm pretty sure I had tried to do this for v2, but something (the real reason eludes me) was blocking it. Might have been something to do with Auto.

Feel free to send a PR if you need this soon, or I can tackle it sometime this week.

**Comment by chrylis** [comment]
Right now I'm working around it, it's just really clunky (because Groovy's trying to infer the most specific type for `V` it can and I have to constantly override it).
