### ISSUE TITLE
When will 2.0.0 be cut?

### ISSUE THREAD

**Issue by jamestyrrell** [segmentio/analytics-java#64]
There is a pretty serious bug in 1.0.7 where dispatch causes the Flusher thread to enter a loop. I can see that `Flusher` has been replace in mainline so I am hesitant to submit a patch for the current Flusher if the next release is close to being cut.

**Comment by f2prateek** [comment]
The code is production ready but the API is not as stable as we would like.  I don't have a timeline for 2.0.0 being released yet, but you can use what's on `master`.

**Comment by jamestyrrell** [comment]
If I submitted a patch to fix an issue in the 1.0.7 release would you be able to cut a 1.0.8 release?
