### ISSUE TITLE
Flusher#sendBatch stuck in a loop with 100% CPU

### ISSUE THREAD

**Issue by madisp** [segmentio/analytics-java#71]
I've noticed that an application had a 100% spinning thread while it should've been idle. The culprit turned out to be segmentio's Flusher thread.

I'm not familiar with the codebase but I took a stab at figuring out what went wrong.

Jstack output:

```
"Thread-15" #45 prio=5 os_prio=31 tid=0x00007fa8a10a7000 nid=0x7503 runnable [0x0000000125c73000]
   java.lang.Thread.State: RUNNABLE
	at com.github.segmentio.flush.Flusher.sendBatch(Flusher.java:110)
	at com.github.segmentio.flush.Flusher.run(Flusher.java:77)
```

Code for sendBatch:
```java
private void sendBatch(List<BasePayload> current) {
	boolean success = true;
	int retryCount = 0;
	
	do {
		try {
			if (current.size() > 0) {
				// we have something to send in this batch
				logger.debug("Preparing to send batch.. [{} items]", current.size());
				Batch batch = factory.create(current);
				client.getStatistics().updateFlushAttempts(1);
				success=requester.send(batch);
				logger.debug("Initiated batch request .. [{} items]", current.size());	
				current = new LinkedList<BasePayload>();
			}
		} catch (RuntimeException e) {
			// We will log and loop back around, so we 
			logger.error("Unexpected error while sending batch, catching so we don't lose records", e);
			retryCount++;
			success=false;
		}
	}
	while (!success && retryCount < 3);
	
	if (!success) {
		logger.error("Unable to send batch after {} retries. Giving up on this batch.", retryCount);
	}
	
}
```

It looks like the busy loop is borken - if `requester.send(batch);` fails but doesn't throw then `success` gets set to false, the `current` list will get emptied and `retryCount` won't get incremented (since nothing was thrown).

And now we basically have the following loop:

```java
do {
  if (current.size() > 0) { // always false
  }
}
while (!success && retryCount < 3); // always true
```

this makes my CPU sad :cry:

**Comment by madisp** [comment]
Oh yes, this was 'com.github.segmentio:analytics:1.0.7'

**Comment by daniel-anjos-zeroturnaround** [comment]
Our team also have experienced similar issues with this version. (100% CPU on machine without access to segment.io servers)

Since v1.0.7 is the last public release (specially last with Java 6 support) we are also very interested in this fix.

**Comment by f2prateek** [comment]
This was a bug in v1 which is deprecated, and has been fixed in v2. You can fork v2 if you need Java 6 support.

**Comment by madisp** [comment]
so the latest version in maven central is deprecated?

**Comment by f2prateek** [comment]
No http://search.maven.org/#artifactdetails%7Ccom.segment.analytics.java%7Canalytics-parent%7C2.0.0-RC1%7Cpom
