### ISSUE TITLE
want bugfixes for 1.0.x version?

### ISSUE THREAD

**Issue by benhardy** [segmentio/analytics-java#78]
Hi folks, 

I have a fix for a bug present in 1.0.7, for which we are using a local patch. I would like to share this patch. It addresses a pretty serious connection pool management bug, which bit us when we upgraded some internal services to Jetty 9.3, to which the Segmentio library talks.

Are you accepting changes for this line, even though 2.x is in development? If so, which branch should they be made against?

cheers
b

**Comment by sperand-io** [comment]
@benhardy I can't imagine we wouldn't :) I'll defer to @f2prateek on the mechanics of how we'll bring it in and what branch to open it against, but just wanted to thank you for offering to contribute!

We'll be in touch shortly with next steps

**Comment by benhardy** [comment]
Cheers, my pleasure.

**Comment by f2prateek** [comment]
@benhardy Can you share more details about the patch? Do you have a commit on Github?

**Comment by benhardy** [comment]
Here's a diff against 1.0.7. All it does is make sure HttpResponses get closed. This was enough to ensure that connections in the pool can get reused efficiently. We saw after upgrading some services to Jetty 9.3. that the analytics library would just lock up because it was holding onto connections too long and timing out. This fixes that.

https://github.com/segmentio/analytics-java/compare/analytics-1.0.7...benhardy:1.x

**Comment by madisp** [comment]
We're also operating with a fork that fixes #71. If there is going to be a 1.0.8 I'd be happy to create a PR so it could get in.

**Comment by f2prateek** [comment]
We'll make a 1.0.8 release to accomodate these fixes. I don't have an exact plan yet, but I'll post back with how to proceed. 

I would still highly recommend using the v2 releases (even as a fork if you need Java 6 support). There are significant architectural changes and bug fixes for cases like this.
