### ISSUE TITLE
Custom ThreadFactory

### ISSUE THREAD

**Issue by brimworks** [segmentio/analytics-java#79]
Hello,

I noticed that the ability of specifying a custom ThreadFactory is currently marked as ```@Beta``` and uses "default visibility". Are there any plans of exposing this? Currently we use this functionality to mark the executor threads as "daemon" threads and to give them a custom thread name.

More specifically we are using these API's:
- ```com.segment.analytics.Analytics.Builder.threadFactory(ThreadFactory)```
- ```com.segment.analytics.Platform.defaultThreadFactory()```

...and here is the custom thread factory (so you can see our use-case):

```java
Analytics.builder(writeKey)
            .threadFactory((runnable) -> {
                    Thread thread = Platform.get().defaultThreadFactory().newThread(runnable);
                    thread.setName(String.format("SegmentClient-%d-%d", instanceCount, threadCount));
                    thread.setDaemon(true);
                    return thread;
                })
            .build();
```

Thanks,
-Brian

**Comment by f2prateek** [comment]
I'm not comfortable exposing the Platform class, but I've made the threadFactory configurable in #80.

**Comment by brimworks** [comment]
No problem about exposing the Platform class. The only reason I was using it was so any Segment specific tweaks to the Thread can be done by the ```Platform.defaultThreadFactory()```, just like a best practice when creating a ```ThreadPoolExecutor``` with a custom ```ThreadFactory``` is to use ```Executors.defaultThreadFactory()```.

...so I guess I'll just have to copy the code in the ```defaultThreadFactory()``` implementation that sets the thread priority.

Thanks,
-Brian
