### ISSUE TITLE
Gradle config: compile "com.segment.analytics.java:analytics:+" is broken

### ISSUE THREAD

**Issue by kpse** [segmentio/analytics-java#90]
$ gradle -v

---
## Gradle 2.14

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Mac OS X 10.11.6 x86_64

**Comment by kpse** [comment]
the `gradle` command will report:
```
...
Could not resolve: com.segment.analytics.java:analytics:+
...
```

**Comment by f2prateek** [comment]
I think it's because the RC confuses it. I published a non-TC release today so should be fixed now.
