### ISSUE TITLE
Create an Analytics interface for testing

### ISSUE THREAD

**Issue by thorey** [segmentio/analytics-java#91]
I would like to be able to mock the Analytics class so that I can create unit tests.

Is possible for you to create one or can you recommend an alternate way of testing the Analytics class?

Best wishes,
Thorey

**Comment by f2prateek** [comment]
you can use mockito or one of the other mocking libraries.
`Analytics analytics = mock(Analytics.class);`

Or you can create your own interface around the analytics class.
